### ISSUE TITLE
Do you need a CI system? Any idea about testing? 

### ISSUE THREAD

**Issue by Sulstice** [cthoyt/pybacting#1]

**Comment by cthoyt** [comment]
I'm not really sure where to go next - maybe exposing the CDK object is enough. I just added in d1564eb my standard gamut of CI stuff (excluding docs).

Maybe @egonw has some ideas on what else should go in this package (if anything) and we can come back to this

**Comment by Sulstice** [comment]
Haha, I was about to commit my arsenal of stuff as well before I saw this most recent one. Yeah, keep me loop on this one. It looks awesome!

**Comment by cthoyt** [comment]
I'm going to close this since we've already got the CI set up, but feel free to open any other issues
