### ISSUE TITLE
Enable importing all bacting build artifacts

### ISSUE THREAD

**Issue by cthoyt** [cthoyt/pybacting#4]
Blocked by https://github.com/scijava/scyjava/issues/30 and transitively https://github.com/scijava/jgo/issues/31#issuecomment-548056700

To fix this, we'll have to wait for a new release of `jgo` which includes the finished PR https://github.com/scijava/jgo/pull/62. Then, the issue with scyjava will magically go away. This issue can be closed with an update to pybacting's setup.cfg file to include a minimum version of `jgo`

**Comment by ctrueden** [comment]
In the meantime, since scijava/jgo#62 is now merged, you could test with the latest dev version of jgo from git, and see whether the problem is resolved for you?
